apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-ventas
  namespace: innovatech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-ventas
  template:
    metadata:
      labels:
        app: backend-ventas
    spec:
      containers:
        - name: backend-ventas
          image: 098350412874.dkr.ecr.us-east-1.amazonaws.com/backend-ventas:22b29cb
          ports:
            - containerPort: 8080
          env:
            - name: DB_ENDPOINT
              value: "mysql-service"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "innovatech"
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              value: "Innovatech2026"
              #valueFrom:
              #  secretKeyRef:
              #    name: mysql-secret
              #    key: MYSQL_ROOT_PASSWORD
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          #livenessProbe:
          #  httpGet:
          #    path: /actuator/health
          #    port: 8080
          #  initialDelaySeconds: 20
          #  periodSeconds: 10